@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package org.mineplugin.locusazzurro.pyrotechnicraft.world.block;
import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;