
modLoader="javafml"
loaderVersion="${loader_version_range}"
license="ExGPL"

[[mods]] #mandatory
modId="pyrotechnicraft"
version="${mod_version}"
displayName="${mod_name}"
logoFile="pyrotechnicraft.png"
#credits="" #optional
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.pyrotechnicraft]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.pyrotechnicraft]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"