
modLoader="javafml"
loaderVersion="${loader_version_range}"
license="GPL-3.0"
#issueTrackerURL="https://github.com/Example/Example/issues"
[[mods]] #mandatory
modId="pyrotechnicraft"
version="${mod_version}"
displayName="${mod_name}"
#logoFile="examplemod.png" #optional
#credits="" #optional
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.pyrotechnicraft]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.pyrotechnicraft]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"